// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GeocodingData, GeocodingResponses, ReverseData, ReverseResponses, StatusData, StatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get coordinates for address
 */
export const geocoding = <ThrowOnError extends boolean = false>(options: Options<GeocodingData, ThrowOnError>): RequestResult<GeocodingResponses, unknown, ThrowOnError> => (options.client ?? client).get<GeocodingResponses, unknown, ThrowOnError>({ url: '/api', ...options });

/**
 * Get address for coordinates
 */
export const reverse = <ThrowOnError extends boolean = false>(options: Options<ReverseData, ThrowOnError>): RequestResult<ReverseResponses, unknown, ThrowOnError> => (options.client ?? client).get<ReverseResponses, unknown, ThrowOnError>({ url: '/reverse', ...options });

/**
 * Get service status
 */
export const status = <ThrowOnError extends boolean = false>(options?: Options<StatusData, ThrowOnError>): RequestResult<StatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<StatusResponses, unknown, ThrowOnError>({ url: '/status', ...options });
