// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://photon.komoot.io' | (string & {});
};

export type PhotonFeature = {
    type: 'Feature';
    geometry: {
        type: 'Point';
        coordinates: [
            number,
            number
        ];
    };
    properties: {
        osm_id: number;
        osm_type: string;
        extent?: Array<number>;
        country?: string;
        osm_key?: string;
        city?: string;
        osm_value?: string;
        postcode?: string;
        name?: string;
        state?: string;
        street?: string;
        housenumber?: string;
    };
};

export type PhotonFeatureCollection = {
    type: 'FeatureCollection';
    features: Array<PhotonFeature>;
};

export type Status = {
    status: string;
    import_date: string;
};

export type GeocodingData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        /**
         * describes how much the prominence of a result should still be taken into account (0.0 to 1.0)
         */
        location_bias_scale?: number;
        /**
         * Describes the radius around the center to focus on. This influences location bias.
         */
        zoom?: number;
        limit?: number;
        osm_tag?: string;
        lang?: string;
        lon?: number;
        lat?: number;
        bbox?: string;
    };
    url: '/api';
};

export type GeocodingResponses = {
    200: PhotonFeatureCollection;
};

export type GeocodingResponse = GeocodingResponses[keyof GeocodingResponses];

export type ReverseData = {
    body?: never;
    path?: never;
    query: {
        lon: number;
        lat: number;
        /**
         * Maximum number of features
         */
        limit?: number;
        /**
         * Maximum radius in km
         */
        radius?: number;
        distance_sort?: boolean;
    };
    url: '/reverse';
};

export type ReverseResponses = {
    200: PhotonFeatureCollection;
};

export type ReverseResponse = ReverseResponses[keyof ReverseResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type StatusResponses = {
    200: Status;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];
